repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.13.1
    hooks:
      - id: helm-docs
        args:
          # The `./` makes it relative to the chart-search-root set above
          - --template-files=../_templates.gotmpl

          # Document our dependency values
          - --document-dependency-values

          # Sort values based on file order, not alphanumeric
          #- --sort-values-order=file

          # Increase log level to try to figure out why it's marking as failed
          # - --log-level=trace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
